--- 
  #Playbook to deploy whole app stack ibn this site

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

- name: configure and deploy webservers and app code
  hosts: webservers
  remote_user: root

  roles:
    - web
  
  
- name: deploy MySQL and cxonfigure the databases
  hosts: dbservers
  remote_user: root

  roles:
    - db